version: 0.2

env:
  secrets-manager:
    hydra_npm_token: hydra_npm:token
  exported-variables:
    - CODEBUILD_BUILD_NUMBER
phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto11
    commands:
  pre_build:
    commands:
      - cd access-checkout-react-native-sdk
      - ./scripts/deploy/set-npm-token.sh
  build:
    commands:
      - echo "Publishing React Native SDK..."
      - ./scripts/publish.sh -d=prod
  post_build:
    commands:
      - ./scripts/deploy/remove-npm-token.sh
      - ./scripts/deploy/slack-notification.sh
