{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worldpay.access",
    "module": "access-checkout-android",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266081,
          "sha512": "041113b3e7053318247bf4e2c41bfbb194fdb8096ba6867c3ed1cc7a235d3fd07146e726831333df5625473746c5b83117e3f8e94e8621c0eea8c402a49066aa",
          "sha256": "2c3eedc686f92993b83ced240cb78601930719c644ee48a6c7927f2610338fa9",
          "sha1": "8a15f9372e8142f5fc60489a07f86998c1062931",
          "md5": "c07210d82fa70cd0bf10740ccee4c302"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266081,
          "sha512": "041113b3e7053318247bf4e2c41bfbb194fdb8096ba6867c3ed1cc7a235d3fd07146e726831333df5625473746c5b83117e3f8e94e8621c0eea8c402a49066aa",
          "sha256": "2c3eedc686f92993b83ced240cb78601930719c644ee48a6c7927f2610338fa9",
          "sha1": "8a15f9372e8142f5fc60489a07f86998c1062931",
          "md5": "c07210d82fa70cd0bf10740ccee4c302"
        }
      ]
    }
  ]
}
