{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worldpay.access",
    "module": "access-checkout-android",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266253,
          "sha512": "189b4a31dd9ee65610ac30fef715bcdd8c393f65fccefbe923c6bb7ede65eb44fac56b01e328df6b507dfa12c1bed98dc0b6c7a50028f43f47c56e3d9ece3f9f",
          "sha256": "b47e701cdbe2d67765ce438d393e1b8489f96858f8af52df04beae8808bcc7cc",
          "sha1": "989d983f4471181d2de378aca39dc3680f9db367",
          "md5": "ce89c7cf47e5514d4dc850eb4fc91d80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266253,
          "sha512": "189b4a31dd9ee65610ac30fef715bcdd8c393f65fccefbe923c6bb7ede65eb44fac56b01e328df6b507dfa12c1bed98dc0b6c7a50028f43f47c56e3d9ece3f9f",
          "sha256": "b47e701cdbe2d67765ce438d393e1b8489f96858f8af52df04beae8808bcc7cc",
          "sha1": "989d983f4471181d2de378aca39dc3680f9db367",
          "md5": "ce89c7cf47e5514d4dc850eb4fc91d80"
        }
      ]
    }
  ]
}
