{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worldpay.access",
    "module": "access-checkout-android",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266448,
          "sha512": "5992590e836270c3dec0b53bdc4be41411dbc0afde423e38a6df12f1e77339bf81c8ab1057f967a18dd8dd29ef8b034369e5a3faa9370672d2e704e304f8959e",
          "sha256": "eb4fae0bbfcf2473b909c1783b2d341ecb7d2f65608c58e3ee96b813a93474e7",
          "sha1": "fa60a9e9155b6d6e90f459f9fb0a181afd5897a8",
          "md5": "d84223955fcfbfe00e34ee6949fcf269"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "access-checkout-android-3.0.0.aar",
          "url": "access-checkout-android-3.0.0.aar",
          "size": 266448,
          "sha512": "5992590e836270c3dec0b53bdc4be41411dbc0afde423e38a6df12f1e77339bf81c8ab1057f967a18dd8dd29ef8b034369e5a3faa9370672d2e704e304f8959e",
          "sha256": "eb4fae0bbfcf2473b909c1783b2d341ecb7d2f65608c58e3ee96b813a93474e7",
          "sha1": "fa60a9e9155b6d6e90f459f9fb0a181afd5897a8",
          "md5": "d84223955fcfbfe00e34ee6949fcf269"
        }
      ]
    }
  ]
}
