require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AccessCheckoutReactNative' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'AccessCheckoutSDK', '~> 2.3.0'
end

target 'AccessCheckoutReactNativeUnitTests' do
  use_frameworks!
  config = use_native_modules!
 
  use_react_native!(:path => config["reactNativePath"])
 
  pod 'Mockingjay', '~> 3.0.0-alpha.1'
end
