require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AccessCheckoutReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'AccessCheckoutSDK', :path => ENV['ACCESS_CHECKOUT_IOS_PATH']
end

target 'AccessCheckoutReactNativeUnitTests' do
 config = use_native_modules!

 use_react_native!(:path => config["reactNativePath"])
end
