#!/bin/bash

rootDir=$(pwd)

# checks on SDK code
changesInSdk=$(git status ./access-checkout-react-native-sdk --porcelain | wc -l)
if [ $changesInSdk -ne 0 ]; then
  set -e

  cd access-checkout-react-native-sdk

  echo "Checking linting on SDK"
  npm run lint

  set +e
fi


# checks on demo-app code
cd $rootDir

changesInApp=$(git status ./demo-app --porcelain | wc -l)
if [ $changesInApp -ne 0 ]; then
  set -e

  cd demo-app

  echo "Checking linting on demo-app"
  npm run lint

  set +e
fi

exit 0
