name: bump-version-script
run-name: Bump version of SDK to ${{inputs.version}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (x.y.z)'
        required: true
      rally_ticket_number:
        description: 'Rally ticket number (USxxxxxxx)'
        required: true
jobs:
  run-bump-version-script:
    runs-on: macos-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run bump version script
        run: ./scripts/bump-version.sh -v=${{inputs.version}} -t=${{inputs.rally_ticket_number}}
